---
title: "R Notebook"
output: html_notebook
---



```{r}

library(dplyr)
library(readr)
library(lubridate)
library(broom)
library(Metrics)
library(e1071)
library(ggplot2)


umsatzdaten <- read_csv("umsatzdaten_gekuerzt.csv")
wetter <- read_csv("wetter.csv")
kiwo <- read_csv("kiwo.csv")
feiertage <- read_delim("feiertage.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)


#Zusammenfügen der Daten und Anfügen weiterer Variablen
#Test
vumsatz <- left_join(umsatzdaten,kiwo)
vumsatz[is.na(vumsatz$KielerWoche),]$KielerWoche<-0
vumsatz=left_join(vumsatz,wetter)
#View(feiertage)
#View(vumsatz)
vumsatz=left_join(vumsatz,feiertage)
vumsatz=subset(vumsatz,select=-c(Heiligerabend_dummy,Silvester_dummy))
#Kodieren des Wetters in einer Variablen
vumsatz$Wetter <- 0
vumsatz[is.na(vumsatz$Wettercode),]$Wetter = 1
vumsatz$Feiertag_Ja=0
vumsatz[is.na(vumsatz$Feiertag),]$Feiertag_Ja = 1
vumsatz[is.na(vumsatz$Feiertag),]$Feiertag = "Nein"
vumsatz$Wochentag <- weekdays(as.Date(vumsatz$Datum))

#Löschen von Zeilen mit NA-Einträgen oder ersetzen durch unsinnige Werte
vumsatz=vumsatz[!is.na(vumsatz$Temperatur),]
vumsatz[is.na(vumsatz$Wettercode),]$Wettercode=-1
vumsatz[is.na(vumsatz$Bewoelkung),]$Bewoelkung=-1
vumsatz$Tag = yday(as.Date(vumsatz$Datum))
#Testen, ob Datensatz NA enthält
#View(vumsatz)
any(is.na(vumsatz$Datum))
any(is.na(vumsatz$Umsatz))
any(is.na(vumsatz$Warengruppe))
any(is.na(vumsatz$KielerWoche))

any(is.na(vumsatz$Temperatur))
any(is.na(vumsatz$Bewoelkung))
any(is.na(vumsatz$Wettercode))
any(is.na(vumsatz$Windgeschwindigkeit))
any(is.na(vumsatz$Wochentag))
any(is.na(vumsatz$Wetter))
any(is.na(vumsatz$Tag))
any(is.na(vumsatz$Feiertag))
any(is.na(vumsatz$Feiertag_Ja))

data_predict=left_join(wetter,kiwo)
data_predict=left_join(data_predict,umsatzdaten)
data_predict=left_join(data_predict,feiertage)
data_predict=subset(data_predict,select=-c(Heiligerabend_dummy,Silvester_dummy))
data_predict$Wetter <- 0
data_predict[is.na(data_predict$Wettercode),]$Wetter = 1
data_predict$Feiertag_Ja=0
data_predict[is.na(data_predict$Feiertag),]$Feiertag_Ja = 1
data_predict[is.na(data_predict$Feiertag),]$Feiertag = "Nein"
data_predict$Wochentag <- weekdays(as.Date(data_predict$Datum))
data_predict=data_predict[!is.na(data_predict$Temperatur),]
data_predict[is.na(data_predict$Wettercode),]$Wettercode=-1
data_predict[is.na(data_predict$Bewoelkung),]$Bewoelkung=-1
data_predict$Tag = yday(as.Date(data_predict$Datum))
data_predict[is.na(data_predict$Umsatz),]$Umsatz=0
data_predict[is.na(data_predict$Warengruppe),]$Warengruppe=0
data_predict[is.na(data_predict$KielerWoche),]$KielerWoche<-0



temptest = vumsatz
temptest$Jahr = year(as.Date(temptest$Datum))
temptest$Monat = month(as.Date(temptest$Datum))

Jahre = seq(2013,2019)
Monate = seq(1,12)

temptest$T_Abweichung = 0
for(j in 1:7){
  for(i in 1:12){
    for(k in 1:6){
      selected_data = temptest$Warengruppe == k & temptest$Jahr == 2012+j & temptest$Monat == i
      data = temptest[selected_data,]
      temp_mean = mean(data$Temperatur)
      temptest[selected_data,]$T_Abweichung = temptest[selected_data,]$Temperatur-temp_mean
    }
  }
}

vumsatz$T_Abweichung = temptest$T_Abweichung

temptest = data_predict
temptest$Jahr = year(as.Date(temptest$Datum))
temptest$Monat = month(as.Date(temptest$Datum))

Jahre = seq(2013,2019)
Monate = seq(1,12)

temptest$T_Abweichung = 0
for(j in 1:7){
  for(i in 1:12){
    for(k in 1:6){
      selected_data = temptest$Warengruppe == k & temptest$Jahr == 2012+j & temptest$Monat == i
      data = temptest[selected_data,]
      temp_mean = mean(data$Temperatur)
      temptest[selected_data,]$T_Abweichung = temptest[selected_data,]$Temperatur-temp_mean
    }
  }
}

data_predict$T_Abweichung = temptest$T_Abweichung

```
```{r}
# Zufallszähler setzen (um die zufällige Partitionierung bei jedem Durchlauf gleich zu halten)
set.seed(1)

# Zufällige Ziehung Indizes für die Zeilen des Datensatzes, die dem Traininsdatensatz zugeordnet werden
indices_train <- sample(seq_len(nrow(vumsatz)), size = floor(0.80 * nrow(vumsatz)))

# Definition des Trainings- und Testdatensatz durch Selektion bzw. Deselektion der entsprechenden Datenzeilen
umsatz_train <- umsatz_train_org <- vumsatz[indices_train, ]
umsatz_test <- vumsatz[-indices_train, ]


#Verkleinerung des Datensatzes zu Testzwecken
umsatz_train <- sample_frac(umsatz_train_org, .20)
# warengruppe=1
# umsatz_train=umsatz_train[umsatz_train$Warengruppe==warengruppe,]
# umsatz_test=umsatz_test[umsatz_test$Warengruppe==warengruppe,]
```


```{r}
#Berechnen von linearem Modell
# mod2 <-
#   lm(
#     Umsatz ~ as.factor(Feiertag_Ja) + Temperatur + as.factor(KielerWoche) + as.factor(Wochentag) +
#       as.factor(Wetter) + Tag + Bewoelkung,
#     umsatz_train
#   )
# 
# mape(umsatz_train$Umsatz, predict(mod2, new_data = umsatz_train))

#Berechnung des svm Modells
svm_tune <-
  tune(
    svm,
    Umsatz ~ as.factor(KielerWoche)+ as.factor(Wetter)*as.factor(Warengruppe) + Temperatur*as.factor(Warengruppe) + as.Date(Datum)*as.factor(Warengruppe)  + as.factor(Wochentag)*as.factor(Warengruppe)+T_Abweichung*as.factor(Warengruppe),
    data = umsatz_train,
    ranges = list(epsilon = seq(0.1, 1, 0.1), cost = 2 ^ (0:3))
  )


#Errechnen des relativen Fehlers für Trainingsdaten
pred_best <- predict(svm_tune$best.model, umsatz_train)
mape(umsatz_train$Umsatz, pred_best)

#Errechnen des relativen Fehlers für Testdaten
test_best <- predict(svm_tune$best.model, umsatz_test)
mape(umsatz_test$Umsatz, test_best)

#Darstellen der Daten
vumsatz_plot <- vumsatz[]
vumsatz_plot$Jahr = year(as.Date(vumsatz_plot$Datum))
vumsatz_plot$svm <- predict(svm_tune$best.model, vumsatz_plot)
ggplot(vumsatz_plot) + geom_point(aes(x = Datum, y = Umsatz, color = "red")) +
  geom_line(aes(x = Datum, y = svm))
```
```{r}


# mape(vumsatz[vumsatz$Warengruppe==2,]$Umsatz, predict(svm_tune$best.model, vumsatz)[vumsatz$Warengruppe==2])
# mape(vumsatz[vumsatz$Warengruppe==3,]$Umsatz, predict(svm_tune$best.model, vumsatz)[vumsatz$Warengruppe==3])
# mape(vumsatz[vumsatz$Warengruppe==4,]$Umsatz, predict(svm_tune$best.model, vumsatz)[vumsatz$Warengruppe==4])
# mape(vumsatz[vumsatz$Warengruppe==5,]$Umsatz, predict(svm_tune$best.model, vumsatz)[vumsatz$Warengruppe==5])
# mape(vumsatz[vumsatz$Warengruppe==6,]$Umsatz, predict(svm_tune$best.model, vumsatz)[vumsatz$Warengruppe==6])


 #Umsatz ~ as.factor(KielerWoche)+ as.factor(Wetter)*as.factor(Warengruppe) + Temperatur*as.factor(Warengruppe) + as.Date(Datum)*as.factor(Warengruppe)  + as.factor(Wochentag)*as.factor(Warengruppe),
 

dumsatz = NULL
umsatz_error = NULL
for(warengruppe in 1:5){
  gdata_predict=data_predict
  gdata_predict[gdata_predict$Warengruppe==0,]$Warengruppe=warengruppe
  #gdata_predict=subset(data_predict,select=c(Datum,Wetter,Warengruppe,KielerWoche,Temperatur,Wochentag,Umsatz))
  vumsatz1<-predict(svm_tune$best.model,gdata_predict)
  dumsatz=rbind(dumsatz,vumsatz1[gdata_predict$Datum=="2019-06-04"])
  umsatz_error = rbind(umsatz_error,mape(vumsatz[vumsatz$Warengruppe==warengruppe,]$Umsatz, predict(svm_tune$best.model, vumsatz)[vumsatz$Warengruppe==warengruppe]))
}

umsatz_error = rbind(umsatz_error,mape(vumsatz[vumsatz$Warengruppe==6,]$Umsatz, predict(svm_tune$best.model, vumsatz)[vumsatz$Warengruppe==6]))
```

```{r}

data <- data.frame(
  name=c(1,2,3,4,5,6),
  value=umsatz_error
)

# Uniform color
xx<-barplot(height=data$value, names=data$name, 
        col=rgb(0.8,0.1,0.1,0.6),
        xlab="Warengruppe", 
        ylab="MAPE", 
        main="MAPE svm je Warengruppe", 
        ylim=c(0,1)
        )

text(x = xx, y = data$value, label = round(data$value,digits=2), pos = 3, cex = 0.8, col = "red")

```

```{r}
# create a dataset
Methode <- c(rep("svm" , 5) )
Warengruppe <- rep(c("1" , "2" , "3", "4", "5"),1) 
Wert <- dumsatz
data <- data.frame(specie,Warengruppe,Wert)
 
# Stacked
ggplot(data, aes(fill=Warengruppe, y=Wert, x=Methode,label =round(Wert,digits=1))) + 
    geom_bar(position="stack", stat="identity")+
  geom_text(size = 3, position = position_stack(vjust = 0.5))
```

